# Generated by Django 4.1.2 on 2022-10-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=225)),
                ('age', models.CharField(max_length=225)),
                ('gender', models.CharField(max_length=225)),
            ],
        ),
    ]
