# Generated by Django 4.1.2 on 2022-10-19 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='age',
        ),
        migrations.RemoveField(
            model_name='members',
            name='course',
        ),
        migrations.RemoveField(
            model_name='members',
            name='gender',
        ),
    ]
