# Generated by Django 4.1.2 on 2022-10-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_members_preferred_course_members_email_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='mobile_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='total_marks_scored',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='email_id',
            field=models.EmailField(default='some string', max_length=236),
        ),
        migrations.AlterField(
            model_name='members',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
    ]
